#ifndef _BUILD_BUILD_INFOS_H_INCLUDED_
#define _BUILD_BUILD_INFOS_H_INCLUDED_
#define BUILD_ARCH "armv8"
#define BUILD_CPU "cortex-a53"
#define BUILD_PLAT "b1_msoc"
#define BUILD_KERNEL_REVISION "488203c4b538"
#define BUILD_KERNEL_FLAVOR ""
#define BUILD_KERNEL_VERSION "488203c4b538 B1 b1_v0.3.0_delivery provencore-src"
#define BUILD_KERNEL_MODIFIED 0
#define BUILD_SERVICES_REVISION "69a30ce6012d"
#define BUILD_SERVICES_VERSION "69a30ce6012d B1 services-src"
#define BUILD_SERVICES_MODIFIED 0
#endif /* _BUILD_BUILD_INFOS_H_INCLUDED_ */
