[package]
name = "eth"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib"]
path = "src/lib.rs"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
pnc = { path = "../pnc-rs" }
pnc-device = { path = "../pnc-device" }
